version: '3.6'

services:
  chatbot:
    build: .
    ports:
      - 3001:3000
    env_file:
      - .env.local
    depends_on:
      - couchdb
    networks:
      - chatbot

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'chatbotui'
      MYSQL_USER: 'chatbotui'
      MYSQL_PASSWORD: 'P@ssw0rd'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
    ports:
      - '3316:3306'
    volumes:
      - mysql:/var/lib/mysql

  couchdb:
    image: couchdb:3
    ports:
      - 5984:5984
    volumes:
      - ./couchdb.ini:/opt/couchdb/etc/local.d/00-local.ini
      # - './data:/opt/couchdb/data'
    env_file:
      - .env.local
    networks:
      - chatbot

networks:
  chatbot:

volumes:
  mysql:
