version: '3.6'

services:
  chatbot:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env.local
    depends_on:
      - couchdb
    networks:
      - chatbot

  couchdb:
    image: couchdb:3
    restart: unless-stopped
    volumes:
      - ./couchdb.ini:/opt/couchdb/etc/local.d/00-local.ini
      - couchdb:/opt/couchdb/data
    env_file:
      - .env.local
    networks:
      - chatbot

networks:
  chatbot:

volumes:
  couchdb: